### ISSUE TITLE
snpflip issues

### ISSUE THREAD

**Issue by DM2016** [biocore-ntnu/snpflip#2]
Hello,
I am having a problem with the snpflip code.  When I run it, I use the following command:

snpflip --bim-file=CGEMS_LC_HumanHap550_FW_sample_level_c2_All_final.bim --fasta-genome=HG19.genome.fa

However, I'm getting the following error:

Traceback (most recent call last):
  File "/home/diego/Functions/GSE47718practice/SRPfiles/sratoolkit.2.5.1-centos_linux64/bin/snpflip", line 40, in <module>
    from snp_flip.table import create_snp_table, find_strand
ImportError: No module named snp_flip.table

I'm looking for this module and can't find it.  Can anyone please help me with this error?
Best,
DM

**Comment by endrebak** [comment]
here it is:
https://github.com/biocore-ntnu/snpflip/blob/master/snp_flip/table.py

How did you install the software? Pip install snpflip?

**Comment by endrebak** [comment]
I'll take it that pip install snpflip worked then.
