### ISSUE TITLE
Running snpflip

### ISSUE THREAD

**Issue by mircea83** [biocore-ntnu/snpflip#5]
Hi, 

I cannot unfortunately run snpflip on the mac terminal, maybe it is because I am a beginner with python. I had python installed already, I have used sudo pip to install Biopython and snpflip, but the snpflip command simply does not work. The module appears in the list of python modules installed (as snp_flip). The snp_flip directory contains the following files, both as .py and .pyc: _init_, bim_file, reference_genome, table, version. I have tried to import it (import snp_flip), but still the snpflip command does not work. I have both my bim file and the reference genome in fasta format (.fasta) in the current directory. I really need to use this programme to flip strand my gwas dataset using hg18 as reference. Any idea what am I doing wrong? Many many thanks!

**Comment by endrebak** [comment]
Thanks for asking :)

`snpflip` is run from the command line, not the Python interpreter.

If this is not your problem, what is the result of `echo $PATH`? And `which python` and `python --version`? These are commands you should write in your terminal.

**Comment by mircea83** [comment]
Thanks, it worked, it was that easy :)

What does "There were 1 'N' nucleotides in chromosome 2" mean? I saw from your example that it would suggest NN for a SNP. But I checked through my BIM files and there are no Ns instead of alleles, even if the terminal output suggests this for several chromosomes.

Very grateful for this, really useful!

**Comment by endrebak** [comment]
The Ns are from the fasta. So where your bim says X or Y, the fast just says N. This might mean you are not using the right genome build :)

**Comment by euruijia** [comment]
Hello,
I have the same problem.I cannot run snpflip on the linux terminal. I did my hard work and read all the relevant replies but still don't know how to run. I really need to convert my data now. How do you run these instructions? Not in the terminal snpflip -- instructions? Thank you very much!
