### ISSUE TITLE
Running snpflip

### ISSUE THREAD

**Issue by rvbn** [biocore-ntnu/snpflip#7]
Hello,

I am trying to run snpflip on my Ubuntu terminal, but I keep getting this error:
snpflip: command not found

I believe I have downloaded snpflip. 
$ sudo apt install python-pip
$ pip install snpflip

This is my output:
Collecting snpflip
  Downloading https://files.pythonhosted.org/packages/5d/58/c4e3427cd307c29c92631f0d2bc0ee599687d1d29019a390d9786ec6a44e/snpflip-0.0.6.tar.gz
Collecting docopt (from snpflip)
  Downloading https://files.pythonhosted.org/packages/a2/55/8f8cab2afd404cf578136ef2cc5dfb50baa1761b68c9da1fb1e4eed343c9/docopt-0.6.2.tar.gz
Collecting ebs (from snpflip)
  Downloading https://files.pythonhosted.org/packages/5d/70/9b2c73d81942724b0fbfc85c01bcafc8509a98c3210f5c5c89bca0f076ae/ebs-0.0.10.tar.gz
Collecting natsort (from snpflip)
  Downloading https://files.pythonhosted.org/packages/e3/31/b937f858addee2e1a62f15842f0f3f07e9277aa87fb67fe9b9e28ac90d50/natsort-5.4.1-py2.py3-none-any.whl
Collecting pandas>=0.16 (from snpflip)
  Downloading https://files.pythonhosted.org/packages/b7/e3/f52d484244105fa3d558ce8217a5190cd3d40536076bef66d92d01566325/pandas-0.23.4-cp27-cp27mu-manylinux1_x86_64.whl (8.9MB)
    100% |████████████████████████████████| 8.9MB 138kB/s 
Collecting pyfaidx (from snpflip)
  Downloading https://files.pythonhosted.org/packages/6c/25/6b6488d613092abdecf58dfc88c72d77c12af39b5d32c3001cdaa34d23cc/pyfaidx-0.5.5.tar.gz
Collecting pytz>=2011k (from pandas>=0.16->snpflip)
  Downloading https://files.pythonhosted.org/packages/30/4e/27c34b62430286c6d59177a0842ed90dc789ce5d1ed740887653b898779a/pytz-2018.5-py2.py3-none-any.whl (510kB)
    100% |████████████████████████████████| 512kB 2.9MB/s 
Collecting numpy>=1.9.0 (from pandas>=0.16->snpflip)
  Downloading https://files.pythonhosted.org/packages/c9/16/1134977cc35d2f72dbe80efa75a8e989ac21289f8e7e2c9005444cd17cd5/numpy-1.15.1-cp27-cp27mu-manylinux1_x86_64.whl (13.8MB)
    100% |████████████████████████████████| 13.8MB 82kB/s 
Collecting python-dateutil>=2.5.0 (from pandas>=0.16->snpflip)
  Downloading https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl (211kB)
    100% |████████████████████████████████| 215kB 5.8MB/s 
Collecting setuptools>=0.7 (from pyfaidx->snpflip)
  Downloading https://files.pythonhosted.org/packages/81/17/a6301c14aa0c0dd02938198ce911eba84602c7e927a985bf9015103655d1/setuptools-40.4.1-py2.py3-none-any.whl (569kB)
    100% |████████████████████████████████| 573kB 2.3MB/s 
Collecting six (from pyfaidx->snpflip)
  Downloading https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Building wheels for collected packages: snpflip, docopt, ebs, pyfaidx
  Running setup.py bdist_wheel for snpflip ... done
  Stored in directory: /home/{username}/.cache/pip/wheels/cc/0e/9b/c4b05d33ffac74254847523b0ed25df0e450e341ae58b00dcc
  Running setup.py bdist_wheel for docopt ... done
  Stored in directory: /home/{username}/.cache/pip/wheels/9b/04/dd/7daf4150b6d9b12949298737de9431a324d4b797ffd63f526e
  Running setup.py bdist_wheel for ebs ... done
  Stored in directory: /home/{username}/.cache/pip/wheels/16/9f/b0/d136df072a69ad41d83cadf95f98eb7371be59b96f31b333ae
  Running setup.py bdist_wheel for pyfaidx ... done
  Stored in directory: /home/{username}/.cache/pip/wheels/74/d5/7f/c23d2f7aee07f93177dcb33239801666a9b4bc8336ba5740dc
Successfully built snpflip docopt ebs pyfaidx
Installing collected packages: docopt, pytz, numpy, six, python-dateutil, pandas, ebs, natsort, setuptools, pyfaidx, snpflip
Successfully installed docopt-0.6.2 ebs-0.0.10 natsort-5.4.1 numpy-1.15.1 pandas-0.23.4 pyfaidx-0.5.5 python-dateutil-2.7.3 pytz-2018.5 setuptools-40.4.1 six-1.11.0 snpflip-0.0.6

Is there a directory I should move to? Thank you for the help.

**Comment by endrebak** [comment]
No, that should be enough. I guess your pip does not go together with the python on your path, but that is just a guess :) Impossible for me to say what is wrong unfortunately

**Comment by rvbn** [comment]
That was right. Thank you for writing and sharing this program.

**Comment by endrebak** [comment]
Feel free to reopen if you have further issues :)
